
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.Random;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nisha
 */
public class WordRush extends javax.swing.JFrame {

    /**
     * Creates new form BlackJack
     */
    public WordRush() {
        initComponents();
    }
    int qwe=0;
    int d=-1;
    int sc=0;
    Random r=new Random();int[] f=new int[100];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ActionListener a = new ActionListener(){
       @Override
            public void actionPerformed(ActionEvent evt){
            int n=jProgressBar1.getValue();
            if(n<100){
            n++;
            jProgressBar1.setValue(n);
            }
            else{
            timer.stop();
            jDialog1.setVisible(true);
           }
            }
    };
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(618, 300));
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog1WindowOpened(evt);
            }
        });

        jButton2.setText("PLAY AGAIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel2.setText("YOU NOW HAVE COMPLETED THE GAME");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(324, 324, 324)
                        .addComponent(jButton3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(150, 150, 150))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1599, 896));
        setPreferredSize(new java.awt.Dimension(1599, 896));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jProgressBar1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(590, 650, 417, 42);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 480, 180, 90);

        jLabel1.setBackground(new java.awt.Color(102, 51, 255));
        jLabel1.setFont(new java.awt.Font("Andalus", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("koje");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 190, 357, 84);

        jTextField1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(620, 340, 357, 68);

        jLabel4.setFont(new java.awt.Font("Bradley Hand ITC", 3, 80)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1310, 120, 200, 130);

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jButton4.setText("Exit");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1360, 730, 180, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon("G:\\oldie\\Aman1\\Exhibition\\Children\\wordrushbgfianl2.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1590, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        timer=new Timer(300,a);
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       d=d+1;
        String w;
        String ans=jTextField1.getText();
        int n=jProgressBar1.getValue();
        String[] words={"mela","amet","arte","kard","wons","drah","awdr","knat","tuer","knba","smca","askm","crsa","ored","outr","lofo","olto","oloc","nomo","onen","ansf","rutn","rtus","sutk","ombb","dren","lapy","aesm","mage","igns","nrai","aetd","mune","ornc","nohr","aeck","albl","ukms","lano","uskh","allh","sone","syee","gsle","ignr","veol","ateh","raes","ihar","edar","ilwd","siwe","oobk","feer","tere","gldo","hdan","ilpc","mozo","jlyu","fmir","owhs","iskd","lelb","yret","becu","otsp","drig","aaer","ndal","regy","eohm","ptan","ianp","niol","lofg","ordo","keaf","actf","ahct","weri","lobd","weiv","thmy","ephl","estw","tasl","oohk","lodl","etcu","arst","eadi","acbk","lecl","gurd"};
        
        int n1=r.nextInt(95);
        int check=0;
        if(d>=1&&d<95){
            while(check>=0&&check<=d-1){
                if(n1==f[check]){
                    n1=r.nextInt(95);
                    check=-1;
                }
                check++;
            }}
        f[d]=n1;
        
         w=words[n1];
        if(ans.equalsIgnoreCase("joke")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
        else if(ans.equalsIgnoreCase("fool")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
        else if(ans.equalsIgnoreCase("loot")||ans.equalsIgnoreCase("tool")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }
        else if(ans.equalsIgnoreCase("lame")||ans.equalsIgnoreCase("male")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }
        else if(ans.equalsIgnoreCase("meat")||ans.equalsIgnoreCase("team")||ans.equalsIgnoreCase("tame")||ans.equalsIgnoreCase("mate")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
        }
         else if(ans.equalsIgnoreCase("rate")||ans.equalsIgnoreCase("tear")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
         else if(ans.equalsIgnoreCase("dark")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
         else if(ans.equalsIgnoreCase("snow")||ans.equalsIgnoreCase("sown")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
         else if(ans.equalsIgnoreCase("hard")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
           }else if(ans.equalsIgnoreCase("draw")||ans.equalsIgnoreCase("ward")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("tank")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("true")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("bank")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("scam")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("mask")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("scar")||ans.equalsIgnoreCase("cars")||ans.equalsIgnoreCase("arcs")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("redo")||ans.equalsIgnoreCase("rode")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("tour")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("moon")||ans.equalsIgnoreCase("mono")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("fans")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("turn")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("rust")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
           jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("tusk")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("bomb")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("cool")||ans.equalsIgnoreCase("loco")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("neon")||ans.equalsIgnoreCase("none")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("nerd")||ans.equalsIgnoreCase("rend")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
         
         
         
         //NEw words
         
         
        else if(ans.equalsIgnoreCase("play")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("same")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("game")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("sign")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("rain")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("date")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("menu")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("corn")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("horn")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("cake")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("ball")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("musk")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("loan")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("husk")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("hall")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("nose")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("eyes")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("legs")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("ring")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("love")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("hate")||ans.equalsIgnoreCase("heat")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("ears")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("hair")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("dare")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("wild")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("wise")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }else if(ans.equalsIgnoreCase("book")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }else if(ans.equalsIgnoreCase("free")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }else if(ans.equalsIgnoreCase("tree")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);}
            else if(ans.equalsIgnoreCase("gold")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);}
            
        else if(ans.equalsIgnoreCase("hand")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);}
            else if(ans.equalsIgnoreCase("clip")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);}
             else if(ans.equalsIgnoreCase("zoom")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
             
             
             //Prashant
             
        else if(ans.equalsIgnoreCase("july")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("firm")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("show")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("disk")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("bell")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("tyre")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("cube")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("stop")||ans.equalsIgnoreCase("tops")||ans.equalsIgnoreCase("post")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("grid")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("area")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("land")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("grey")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("home")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("kind")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("pant")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("pain")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("lion")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("golf")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("door")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
         else if(ans.equalsIgnoreCase("fake")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("fact")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("chat")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("wire")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("bold")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("file")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("view")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("myth")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("help")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("west")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("salt")||ans.equalsIgnoreCase("last")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("hook")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("doll")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("cute")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("star")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("idea")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("back")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("cell")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("drug")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       /* d=d+1;
        String w;
        String ans=jTextField1.getText();
        int n=jProgressBar1.getValue();
        String[] words={"mela","amet","arte","kard","wons","drah","awdr","knat","tuer","knba","smca","askm","crsa","ored","outr","lofo","olto","oloc","nomo","onen","ansf","rutn","rtus","sutk","ombb","dren","lapy","aesm","mage","igns","nrai","aetd","mune","ornc","nohr","aeck","albl","ukms","lano","uskh","allh","sone","syee","gsle","ignr","veol","ateh","raes","ihar","edar","ilwd","siwe","oobk","feer","tere","gldo","hdan","ilpc","mozo","jlyu","fmir","owhs","iskd","lelb","yret","becu","otsp","drig","aaer","ndal","regy","eohm","ptan","ianp","niol","lofg","ordo","keaf","actf","ahct","weri","lobd","weiv","thmy","ephl","estw","tasl","oohk","lodl","etcu","arst","eadi","acbk","lecl","gurd"};
        
        int n1=r.nextInt(95);
        int check=0;
        if(d>=1&&d<95){
            while(check>=0&&check<=d-1){
                if(n1==f[check]){
                    n1=r.nextInt(95);
                    check=-1;
                }
                check++;
            }}
        f[d]=n1;
        
         w=words[n1];
        if(ans.equalsIgnoreCase("joke")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
        else if(ans.equalsIgnoreCase("fool")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
        else if(ans.equalsIgnoreCase("loot")||ans.equalsIgnoreCase("tool")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }
        else if(ans.equalsIgnoreCase("lame")||ans.equalsIgnoreCase("male")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }
        else if(ans.equalsIgnoreCase("meat")||ans.equalsIgnoreCase("team")||ans.equalsIgnoreCase("tame")||ans.equalsIgnoreCase("mate")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
        }
         else if(ans.equalsIgnoreCase("rate")||ans.equalsIgnoreCase("tear")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
         else if(ans.equalsIgnoreCase("dark")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
         else if(ans.equalsIgnoreCase("snow")||ans.equalsIgnoreCase("sown")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
         else if(ans.equalsIgnoreCase("hard")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
           }else if(ans.equalsIgnoreCase("draw")||ans.equalsIgnoreCase("ward")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("tank")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("true")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("bank")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("scam")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("mask")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("scar")||ans.equalsIgnoreCase("cars")||ans.equalsIgnoreCase("arcs")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("redo")||ans.equalsIgnoreCase("rode")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("tour")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("moon")||ans.equalsIgnoreCase("mono")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("fans")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("turn")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("rust")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
           jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("tusk")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("bomb")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("cool")||ans.equalsIgnoreCase("loco")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("neon")||ans.equalsIgnoreCase("none")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("nerd")||ans.equalsIgnoreCase("rend")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }
         
         
         
         //NEw words
         
         
        else if(ans.equalsIgnoreCase("play")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("same")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("game")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("sign")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("rain")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("date")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("menu")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("corn")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("horn")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("cake")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("ball")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("musk")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("loan")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("husk")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("hall")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("nose")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("eyes")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("legs")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("ring")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("love")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("hate")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("ears")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("hair")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("dare")||ans.equalsIgnoreCase("Dear")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("wild")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
         }else if(ans.equalsIgnoreCase("wise")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }else if(ans.equalsIgnoreCase("book")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }else if(ans.equalsIgnoreCase("free")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);
            }else if(ans.equalsIgnoreCase("tree")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);}
            else if(ans.equalsIgnoreCase("gold")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);}
            
        else if(ans.equalsIgnoreCase("hand")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);}
            else if(ans.equalsIgnoreCase("clip")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc);}
             else if(ans.equalsIgnoreCase("zoom")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
             
             
             
             
        else if(ans.equalsIgnoreCase("july")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("firm")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("show")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("disk")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("bell")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("tyre")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("cube")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("stop")||ans.equalsIgnoreCase("opts")||ans.equalsIgnoreCase("tops")||ans.equalsIgnoreCase("post")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("grid")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("area")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("land")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("grey")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("home")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("kind")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("pant")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("pain")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("lion")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("golf")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("door")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
         else if(ans.equalsIgnoreCase("fake")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("fact")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("chat")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("wire")||ans.equalsIgnoreCase("weir")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("bold")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("file")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("view")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("myth")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("help")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("west")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("salt")||ans.equalsIgnoreCase("last")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("hook")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("doll")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("cute")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("star")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("idea")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("back")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("cell")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
        else if(ans.equalsIgnoreCase("drug")){
            n=n-10;
            jProgressBar1.setValue(n);
            jLabel1.setText(w);
            jTextField1.setText("");
            timer.start();
            sc=sc+1;
            jLabel4.setText(""+sc); }
       */
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        WordRush1 e=new WordRush1();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDialog1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowOpened
        // TODO add your handling code here:
        if(qwe==0)
        jLabel2.setText("YOUR SCORE IS: "+sc);
    }//GEN-LAST:event_jDialog1WindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Children1 c1=new Children1();
c1.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            jButton1.doClick();
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        qwe=1;
        timer.stop();
        jDialog1.setVisible(true);
        jLabel2.setText("YOUR SCORE IS: "+sc);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordRush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordRush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordRush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordRush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordRush().setVisible(true);
            }
        });
    }
private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
